use_frameworks!

platform :ios, '14.0'

target 'LiMaoBase_Example' do
  pod 'WuKongBase', :path => '../'

  target 'LiMaoBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
